/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17326.group2.view;

import com.poly.it17326.group2.domainmodel.NhanVien;
import com.poly.it17326.group2.util.DailyCheckingRankCustomer;
import java.awt.Color;
import java.awt.FlowLayout;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class ViewQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form ViewTong
     *
     * @param
     */
    private NhanVien nhanVien = new NhanVien();

    public ViewQuanLy(NhanVien nv) {
        initComponents();
        pnlSanPham.setBackground(Color.WHITE);
        menuSanPham.setForeground(new Color(0, 0, 0));
        nhanVien = nv;
        ViewQuanLySanPham sanPham = new ViewQuanLySanPham();
        pnlQuanLy.removeAll();
        pnlQuanLy.add(sanPham);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);

        DailyCheckingRankCustomer.dailyCheckingRankCustomer();

        ImageIcon imgicon = new ImageIcon("src\\main\\resources\\image\\shoes.png");
        this.setIconImage(imgicon.getImage());

        Thread countDownThread = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");
                do {
                    Date now = new Date();

                    String st = sdf.format(now);

                    lblNgayGio.setText(st);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                } while (true);
            }
        };
        countDownThread.start();

        txtMaNV.setText(nhanVien.getMa());
        txtTenNV.setText(nhanVien.getHoTen());
        txtChucVu.setText(nhanVien.getChucVu().getTen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTong = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        lblNgayGio = new javax.swing.JLabel();
        lblNgayGio1 = new javax.swing.JLabel();
        pnlBanHang = new javax.swing.JPanel();
        menuBanHang = new javax.swing.JLabel();
        pnlSanPham = new javax.swing.JPanel();
        menuSanPham = new javax.swing.JLabel();
        pnlDangXuat = new javax.swing.JPanel();
        menuDangXuat = new javax.swing.JLabel();
        pnlThoat = new javax.swing.JPanel();
        menuThoat = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        menuNhanVien = new javax.swing.JLabel();
        pnlKhuyenMai = new javax.swing.JPanel();
        menuKhuyenMai = new javax.swing.JLabel();
        pnlKhachHang = new javax.swing.JPanel();
        menuKhachHang = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        menuThongKe = new javax.swing.JLabel();
        pnlQuanLy = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenu.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin cá nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 15))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 150));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Mã NV:");

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(255, 0, 0));
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Họ tên:");

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtTenNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Chức vụ:");

        txtChucVu.setEditable(false);
        txtChucVu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtChucVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblNgayGio.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNgayGio.setText("2022-11-23 6:07 PM");

        lblNgayGio1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblNgayGio1.setForeground(new java.awt.Color(255, 102, 102));
        lblNgayGio1.setText("Đổi mật khẩu?");
        lblNgayGio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNgayGio1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMaNV)
            .addComponent(txtTenNV)
            .addComponent(txtChucVu)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayGio)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNgayGio1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgayGio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgayGio1)
                .addGap(7, 7, 7))
        );

        pnlBanHang.setBackground(new java.awt.Color(255, 204, 204));

        menuBanHang.setBackground(new java.awt.Color(255, 255, 255));
        menuBanHang.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBanHang.setText("BÁN HÀNG");
        menuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBanHangMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlBanHangLayout = new javax.swing.GroupLayout(pnlBanHang);
        pnlBanHang.setLayout(pnlBanHangLayout);
        pnlBanHangLayout.setHorizontalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBanHangLayout.setVerticalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        pnlSanPham.setBackground(new java.awt.Color(255, 204, 204));

        menuSanPham.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuSanPham.setText("SẢN PHẨM");
        menuSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        pnlDangXuat.setBackground(new java.awt.Color(255, 204, 204));

        menuDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDangXuat.setText("ĐĂNG XUẤT");
        menuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDangXuatLayout = new javax.swing.GroupLayout(pnlDangXuat);
        pnlDangXuat.setLayout(pnlDangXuatLayout);
        pnlDangXuatLayout.setHorizontalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDangXuatLayout.setVerticalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDangXuatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlThoat.setBackground(new java.awt.Color(255, 204, 204));

        menuThoat.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuThoat.setText("THOÁT");
        menuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThoatLayout = new javax.swing.GroupLayout(pnlThoat);
        pnlThoat.setLayout(pnlThoatLayout);
        pnlThoatLayout.setHorizontalGroup(
            pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlThoatLayout.setVerticalGroup(
            pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThoatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlNhanVien.setBackground(new java.awt.Color(255, 204, 204));

        menuNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuNhanVien.setText("NHÂN VIÊN");
        menuNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNhanVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlKhuyenMai.setBackground(new java.awt.Color(255, 204, 204));

        menuKhuyenMai.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuKhuyenMai.setText("KHUYẾN MÃI");
        menuKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKhuyenMaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlKhuyenMaiLayout = new javax.swing.GroupLayout(pnlKhuyenMai);
        pnlKhuyenMai.setLayout(pnlKhuyenMaiLayout);
        pnlKhuyenMaiLayout.setHorizontalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlKhuyenMaiLayout.setVerticalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhuyenMaiLayout.createSequentialGroup()
                .addComponent(menuKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlKhachHang.setBackground(new java.awt.Color(255, 204, 204));

        menuKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuKhachHang.setText("KHÁCH HÀNG");
        menuKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKhachHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhachHangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlThongKe.setBackground(new java.awt.Color(255, 204, 204));

        menuThongKe.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menuThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuThongKe.setText("THỐNG KÊ");
        menuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongKeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(pnlBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlQuanLyLayout = new javax.swing.GroupLayout(pnlQuanLy);
        pnlQuanLy.setLayout(pnlQuanLyLayout);
        pnlQuanLyLayout.setHorizontalGroup(
            pnlQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLyLayout.setVerticalGroup(
            pnlQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTongLayout = new javax.swing.GroupLayout(pnlTong);
        pnlTong.setLayout(pnlTongLayout);
        pnlTongLayout.setHorizontalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTongLayout.setVerticalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void lblNgayGio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNgayGio1MouseClicked
        new ViewDoiMatKhau(nhanVien, this).setVisible(true);
    }//GEN-LAST:event_lblNgayGio1MouseClicked

    private void menuSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSanPhamMouseClicked
        pnlSanPham.setBackground(Color.WHITE);
        menuSanPham.setForeground(new Color(0, 0, 0));

        menuThongKe.setForeground(Color.BLACK);
        menuBanHang.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlThongKe.setBackground(null);
        pnlBanHang.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlDangXuat.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlThoat.setBackground(null);
        ViewQuanLySanPham sanPham = new ViewQuanLySanPham();
        pnlQuanLy.removeAll();
        pnlQuanLy.add(sanPham);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);
    }//GEN-LAST:event_menuSanPhamMouseClicked

    private void menuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBanHangMouseClicked
        pnlBanHang.setBackground(Color.WHITE);
        menuBanHang.setForeground(new Color(0, 0, 0));

        menuThongKe.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlThongKe.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlDangXuat.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlThoat.setBackground(null);
        ViewBanHang banHang = new ViewBanHang(nhanVien);
        pnlQuanLy.removeAll();
        pnlQuanLy.add(banHang);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);
    }//GEN-LAST:event_menuBanHangMouseClicked

    private void menuBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBanHangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBanHangMouseEntered

    private void menuThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThongKeMouseClicked
        pnlThongKe.setBackground(Color.WHITE);
        menuThongKe.setForeground(new Color(0, 0, 0));

        menuBanHang.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlBanHang.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlDangXuat.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlThoat.setBackground(null);
        ViewThongKe thongKe = new ViewThongKe();
        pnlQuanLy.removeAll();
        pnlQuanLy.add(thongKe);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);
    }//GEN-LAST:event_menuThongKeMouseClicked

    private void menuDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDangXuatMouseClicked
        pnlDangXuat.setBackground(Color.WHITE);
        menuDangXuat.setForeground(new Color(0, 0, 0));

        menuBanHang.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuThongKe.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlBanHang.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlThongKe.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlThoat.setBackground(null);
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất không?", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        new ViewDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDangXuatMouseClicked

    private void menuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThoatMouseClicked
        pnlThoat.setBackground(Color.WHITE);
        menuThoat.setForeground(new Color(0, 0, 0));

        menuBanHang.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuThongKe.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);

        pnlBanHang.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlThongKe.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlDangXuat.setBackground(null);

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chương trình không?", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_menuThoatMouseClicked

    private void menuKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKhachHangMouseClicked
        pnlKhachHang.setBackground(Color.WHITE);
        menuKhachHang.setForeground(new Color(0, 0, 0));

        menuBanHang.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuThongKe.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlBanHang.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlThongKe.setBackground(null);
        pnlDangXuat.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlThoat.setBackground(null);
        ViewKhachHang khachHang = new ViewKhachHang();
        pnlQuanLy.removeAll();
        pnlQuanLy.add(khachHang);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);
    }//GEN-LAST:event_menuKhachHangMouseClicked

    private void menuNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNhanVienMouseClicked
        pnlNhanVien.setBackground(Color.WHITE);
        menuNhanVien.setForeground(new Color(0, 0, 0));

        menuBanHang.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuKhuyenMai.setForeground(Color.BLACK);
        menuThongKe.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlBanHang.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlKhuyenMai.setBackground(null);
        pnlThongKe.setBackground(null);
        pnlDangXuat.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlThoat.setBackground(null);
        ViewNhanVien nhanVien = new ViewNhanVien();
        pnlQuanLy.removeAll();
        pnlQuanLy.add(nhanVien);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);
    }//GEN-LAST:event_menuNhanVienMouseClicked

    private void menuKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKhuyenMaiMouseClicked
        pnlKhuyenMai.setBackground(Color.WHITE);
        menuKhuyenMai.setForeground(new Color(0, 0, 0));

        menuBanHang.setForeground(Color.BLACK);
        menuSanPham.setForeground(Color.BLACK);
        menuNhanVien.setForeground(Color.BLACK);
        menuThongKe.setForeground(Color.BLACK);
        menuKhachHang.setForeground(Color.BLACK);
        menuDangXuat.setForeground(Color.BLACK);
        menuThoat.setForeground(Color.BLACK);

        pnlBanHang.setBackground(null);
        pnlSanPham.setBackground(null);
        pnlNhanVien.setBackground(null);
        pnlThongKe.setBackground(null);
        pnlDangXuat.setBackground(null);
        pnlKhachHang.setBackground(null);
        pnlThoat.setBackground(null);
        ViewKhuyenMai khuyenMai = new ViewKhuyenMai();
        pnlQuanLy.removeAll();
        pnlQuanLy.add(khuyenMai);
        pnlQuanLy.setLayout(new FlowLayout());
        this.pack();
        pnlQuanLy.setVisible(true);
    }//GEN-LAST:event_menuKhuyenMaiMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewQuanLy().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNgayGio;
    private javax.swing.JLabel lblNgayGio1;
    private javax.swing.JLabel menuBanHang;
    private javax.swing.JLabel menuDangXuat;
    private javax.swing.JLabel menuKhachHang;
    private javax.swing.JLabel menuKhuyenMai;
    private javax.swing.JLabel menuNhanVien;
    private javax.swing.JLabel menuSanPham;
    private javax.swing.JLabel menuThoat;
    private javax.swing.JLabel menuThongKe;
    private javax.swing.JPanel pnlBanHang;
    private javax.swing.JPanel pnlDangXuat;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlKhuyenMai;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlQuanLy;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlThoat;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlTong;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
