/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17326.group2.view;

import com.poly.it17326.group2.domainmodel.NhanVien;
import com.poly.it17326.group2.service.DoiMatKhau;
import com.poly.it17326.group2.service.NhanVienService;
import com.poly.it17326.group2.service.impl.DoiMatKhauServiceImpl;
import com.poly.it17326.group2.service.impl.NhanVienServiceImpl;
import com.poly.it17326.group2.util.EmailSender;
import com.poly.it17326.group2.util.MaHoaChuoi;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ViewQuenMatKhau extends javax.swing.JFrame {

    private NhanVienService nhanVienService = new NhanVienServiceImpl();
    private DoiMatKhau doiMatKhau = new DoiMatKhauServiceImpl();
    private Long firstSend = 0L;
    String mxm = "";
    private boolean showMatKhauMoi;
    private boolean showMatKhauMoiP2;

    public ViewQuenMatKhau() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon imgicon = new ImageIcon("src\\main\\resources\\image\\shoes.png");
        this.setIconImage(imgicon.getImage());
        showMatKhauMoi = false;
        showMatKhauMoiP2 = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtMaXacMinh = new javax.swing.JTextField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtNhapLaiMK = new javax.swing.JPasswordField();
        btnDoiMatKhau = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblGuiMaXM = new javax.swing.JLabel();
        lblHTMK1 = new javax.swing.JLabel();
        lblHTMK2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm Mềm Bán Giày Thể Thao ");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shoes.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 470));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUÊN MẬT KHẨU");

        jLabel2.setText("Nhập Email ");

        jLabel3.setText("Mã Xác Minh ");

        jLabel4.setText("Nhập Mật Khẩu Mới ");

        jLabel5.setText("Nhập Lại Mật Khẩu Mới ");

        txtMatKhauMoi.setText("123456");

        txtNhapLaiMK.setText("123456");

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoiMatKhauMouseClicked(evt);
            }
        });
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Đăng Nhập ?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        lblGuiMaXM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gmail.png"))); // NOI18N
        lblGuiMaXM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuiMaXMMouseClicked(evt);
            }
        });

        lblHTMK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hidden.png"))); // NOI18N
        lblHTMK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHTMK1MouseClicked(evt);
            }
        });

        lblHTMK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hidden.png"))); // NOI18N
        lblHTMK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHTMK2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblHTMK2)
                                .addContainerGap())
                            .addComponent(lblHTMK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaXacMinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblGuiMaXM))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnDoiMatKhau))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGuiMaXM, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaXacMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHTMK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHTMK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 400, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGuiMaXMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuiMaXMMouseClicked
        if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống Email");
            return;
        }
        NhanVien nhanVien = nhanVienService.getByEmail(txtEmail.getText());
        if (nhanVien == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy Email");
        } else {
            //Send to Email
            if (firstSend == 0L) {
                mxm = String.valueOf((int) (Math.random() * 100000000));
                EmailSender.emailSender(txtEmail.getText(), "Mã Xác Minh !!!", "Mã xác minh: " + mxm);
                JOptionPane.showMessageDialog(this, "Mã xác minh đã được gửi đến Email");
                firstSend = Calendar.getInstance().getTimeInMillis();
            } else {
                if (firstSend + 60000L > Calendar.getInstance().getTimeInMillis()) {
                    JOptionPane.showMessageDialog(this, "Khoảng thời gian giữa 2 lần gửi mail là 60s");
                } else {
                    mxm = String.valueOf((int) (Math.random() * 100000000));
                    EmailSender.emailSender(txtEmail.getText(), "Mã Xác Minh !!!", "Mã xác minh: " + mxm);
                    firstSend = Calendar.getInstance().getTimeInMillis();
                    JOptionPane.showMessageDialog(this, "Mã xác minh đã được gửi đến Email");
                }
            }
        }
    }//GEN-LAST:event_lblGuiMaXMMouseClicked

    private void btnDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseClicked
        if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống email");
            return;
        }
        if (txtMaXacMinh.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã xác minh");
            return;
        }
        String chkNewPass = txtMaXacMinh.getText().trim();
        System.out.println(mxm);
        if (!chkNewPass.equals(mxm)) {
            JOptionPane.showMessageDialog(this, "Mã xác minh không đúng");
            return;
        }
        if (txtMatKhauMoi.getText().trim().isEmpty() || txtNhapLaiMK.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mật khẩu mới");
            return;
        }
        String pass1 = new String(txtMatKhauMoi.getPassword());
        String pass2 = new String(txtNhapLaiMK.getPassword());
        if (!pass2.equals(pass1)) {
            JOptionPane.showMessageDialog(this, "Hai Password phải giống nhau");
            return;
        }
        String hashPassword = MaHoaChuoi.maHoaMd5(pass2);
        if (nhanVienService.updateMatKhau(hashPassword, txtEmail.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Thành Công");
        }
    }//GEN-LAST:event_btnDoiMatKhauMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new ViewDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblHTMK1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHTMK1MouseClicked
        if (showMatKhauMoi == false) {
            txtMatKhauMoi.setEchoChar((char) 0);
            showMatKhauMoi = true;
            lblHTMK1.setIcon(new ImageIcon("src\\main\\resources\\image\\eye.png"));
        } else {
            txtMatKhauMoi.setEchoChar('*');
            showMatKhauMoi = false;
            lblHTMK1.setIcon(new ImageIcon("src\\main\\resources\\image\\hidden.png"));
        }
    }//GEN-LAST:event_lblHTMK1MouseClicked

    private void lblHTMK2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHTMK2MouseClicked
        if (showMatKhauMoiP2 == false) {
            txtNhapLaiMK.setEchoChar((char) 0);
            showMatKhauMoiP2 = true;
            lblHTMK2.setIcon(new ImageIcon("src\\main\\resources\\image\\eye.png"));
        } else {
            txtNhapLaiMK.setEchoChar('*');
            showMatKhauMoiP2 = false;
            lblHTMK2.setIcon(new ImageIcon("src\\main\\resources\\image\\hidden.png"));
        }
    }//GEN-LAST:event_lblHTMK2MouseClicked

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống email");
            return;
        }
        if (txtMaXacMinh.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã xác minh");
            return;
        }
        String chkNewPass = txtMaXacMinh.getText().trim();
        System.out.println(mxm);
        if (!chkNewPass.equals(mxm)) {
            JOptionPane.showMessageDialog(this, "Mã xác minh không đúng");
            return;
        }
        if (txtMatKhauMoi.getText().trim().isEmpty() || txtNhapLaiMK.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mật khẩu mới");
            return;
        }
        String newPass1 = txtMatKhauMoi.getText();
        String newPass2 = txtNhapLaiMK.getText();
        if (!newPass2.equals(newPass1)) {
            JOptionPane.showMessageDialog(this, "Hai Password phải giống nhau");
            return;
        }
        String hashPassword = MaHoaChuoi.maHoaMd5(newPass2);
        System.out.println(hashPassword);
        if (nhanVienService.updateMatKhau(txtEmail.getText(), hashPassword)) {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại");
        }
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuenMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblGuiMaXM;
    private javax.swing.JLabel lblHTMK1;
    private javax.swing.JLabel lblHTMK2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaXacMinh;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMK;
    // End of variables declaration//GEN-END:variables
}
